#!/usr/bin/env bash

create_pypi()
{
  python3 setup.py sdist bdist_wheel && twine check dist/*
  # cat ~/.pypi && twine upload --repository testpypi dist/*
  echo "Ok."
}

clean_pypi()
{
  rm -rf build && rm -rf dist && rm -rf five_factor_e.egg-info
  echo "Ok."
}

code_style()
{
  black ipipneo/*.py && isort ipipneo/*.py
  black test/*.py && isort test/*.py
}

while [[ "$#" -gt 0 ]]; do
    case ${1} in
        -s|--style) code_style;;
        -p|--pypi) create_pypi;;
        -c|--clean) clean_pypi;;
        *) echo "Unknown parameter!"; exit 1;;
    esac
    shift
done
